<?php
declare(strict_types=1);

namespace AppBundle\Repository;

use AppBundle\Entity\GitHubEntityFactory;
use Doctrine\ORM\EntityRepository;

/**
 * GitHubSearchHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GitHubSearchHistoryRepository extends EntityRepository
{
}
